In [2]:
import pandas as pd

In [3]:
# Read CSV file
df = pd.read_csv(r'C:\Users\a00556457\Repos\personal-time-dashboard-streamlit\data\2024\2024_outlook_data.csv')

In [4]:
df

,Subject,Start Date,Start Time,End Time,Description,End Date,Categories
0,Πτήση IndiGo 925 προς Lucknow (QPVCJV),28/1/2024,09:15:00,11:25:00,"Πτήση IndiGo 925 (2 ώρες, 10 λεπτά)\r\nΚωδικός...",28/1/2024,NaN
1,Αναμονή στο αεροδρόμιο,24/1/2024,08:30:00,11:30:00,\r\n,24/1/2024,Break
2,Πάσχα Ορθόδοξο,5/5/2024,00:00:00,00:00:00,NaN,6/5/2024,NaN
3,Flight to Delhi Delhi Indira Gandhi Intl (DEL)...,24/1/2024,12:15:00,19:40:00,Reservation code: TSBMK2\r\nFlight no: LH 762\...,24/1/2024,NaN
4,Check-in Reminder for your flight to Delhi Del...,23/1/2024,13:15:00,13:45:00,Online Check-in for your flight LH 762 from Mu...,23/1/2024,NaN
...,...,...,...,...,...,...,...
5165,Οικογένεια,31/12/2024,13:30:00,14:00:00,\r\n,31/12/2024,Οικογένεια
5166,Erroneous Tasks (),31/12/2024,12:30:00,13:30:00,\r\n,31/12/2024,Erroneοus Tasks
5167,Οικογένεια,31/12/2024,12:00:00,12:30:00,\r\n,31/12/2024,Οικογένεια
5168,Οικογένεια,31/12/2024,17:00:00,17:30:00,\r\n,31/12/2024,Οικογένεια
5169,Erroneous Tasks (),31/12/2024,17:30:00,18:00:00,\r\n,31/12/2024,Erroneοus Tasks

In [5]:
df.Subject.unique()

array(['Πτήση IndiGo 925 προς Lucknow (QPVCJV)', 'Αναμονή στο αεροδρόμιο',
       'Πάσχα Ορθόδοξο ',
       'Flight to Delhi Delhi Indira Gandhi Intl (DEL) Terminal 3',
       'Check-in Reminder for your flight to Delhi Delhi Indira Gandhi Intl (DEL) Terminal 3',
       'Επέτειος', 'Φαί - Βρες και κλείσε',
       'Συναυλίες, Όπερα, Συμφωνική, Μουσεία, άλλα events',
       'Πτήση SWISS 780 προς Brussels (TSBMK2)',
       'Πτήση SWISS 147 προς Zurich (TSBMK2)',
       'Πτήση Lufthansa 5629 προς Munich (TSBMK2)', 'Αγίου Νεκταρίου ',
       'Γενέθλια Μπαμπάς ',
       'Πτήση Aegean Airlines 620 προς Brussels (M4NJFA)',
       'Γενέθλια Λίλιας', "Γενέθλια 'Αννας", 'Γενέθλια Μουντράκης',
       'Week Ahead Plan Review', 'Easter Monday', 'Εργασία',
       'Copy: Drinks at the chalet, recurring event', 'Labor Day',
       'Pentecost Monday', 'Ascension', 'Γενεθλια Φώτης ', 'Γενέθλια Ερη',
       'Γενέθλια Χριστίνας!', 'Γιορτή Χριστίνας ', 'Γενέθλια Κίμων',
       'Γενέθλια Αποστόλη', 'Taxation Belgium ', 'Μπαμπάς ',
       'Γενέθλια Μάνας ', 'Χαζεύω', 'Ύπνος', '<3', 'Break', 'Οικογένεια',
       'Erroneous Tasks', 'Other', 'Erroneous Tasks (Ινδια Visa)',
       'Εισητήρια (Ινδια Εισητήρια)', 'Erroneous Tasks (Εξέταση Αίματος)',
       'Erroneous Tasks (Τηλέφωνο Στέργιος)', 'Φίλοι (Έρη)', 'Φίλοι ()',
       'vdab', 'Erroneous Tasks (Ραντεβού)', 'Μαγκου Γιατρός 12.45',
       'Erroneous Tasks (KBC Τράπεζες)', 'Erroneous Tasks (Εξέταση IKA)',
       'Μετάφραση', 'Erroneous Tasks (Εμβόλιο Τύφου)', 'Σπίτι',
       'Άφιξη στο Holiday Inn Lucknow Airport, an IHG Hotel', 'Διάβασμα',
       'Οικογένεια (Γιαννούκα)',
       'Αναχώρηση από το Radisson Hotel Varanasi', 'Εισητήρια (Ινδια)',
       'Λάμπρος', 'Erroneous Tasks (Invoices for Month Send to octapus)',
       'Erroneous Tasks (Ασφάλεια Χριστίνας)',
       'Erroneous Tasks (Λογιστής)', 'Εισητήρια (Παρίσι)',
       'Erroneous Tasks (Ινδία)', 'Erroneous Tasks (Νοσοκομείο)',
       'Erroneous Tasks (Mediamarkt Ζυγαριά)',
       'Εισητήρια (Παρίσι - Ινδία)', 'Εισητήρια (Ινδία)',
       'Πτήση IndiGo 6362 προς Delhi (NVJSFT)',
       'Πτήση IndiGo 6236 προς Delhi (RUJ3GW)', 'Ranchi',
       'Erroneous Tasks (Sim Card)', 'Erroneous Tasks (Shopping)',
       'Lucknow', 'Delhi', 'Varanasi', 'Εισητήρια (India)',
       'Pharma Career Day !', 'Bolywood Party', 'Erroneous Tasks ()',
       'Φίλοι (Κίμωνας)', 'Exercise', 'Εισητήρια (Paris)', 'Lampros',
       'Φίλοι (Johan)', '<3 (Βιογραφικά)', 'Βιβλίο Μπαμπά ',
       'Φίλοι (Δουλειά)', 'Wall Painting ', '<3 (Netflix)',
       'Erroneous Tasks (Κούρεμα)',
       'Τσεκαρε τι έγινε με τα λεφτά και κάνε μετά στην wise report για την τσάντα',
       '<3 (Αγορά)', 'Φίλοι (Xavier - Gent)', 'Φίλοι (Βασίλης)',
       'Γάμος Παναγιώτη', '<3 (Black Smoke)', 'Erroneous Tasks ',
       'Φίλοι (Atlas Συναυλία Ρεμπέτικη)  ', '<3 (Rotterdam)',
       '<3 (VDAB)', '<3  () ', 'Σπίτι (Σούπερ)', 'Exercise (Streching)',
       'Φίλοι (Μουσμούλης)', 'Δάσος', 'Γάμος Giatrou', 'Vacation forced',
       'Mastering Interactive Dash Apps with Dash.jl: A Flight Traffic Visualization Journey on JuliaHub',
       'Πτήση Ryanair 4998 προς Brussels (JI4QJF)',
       'Πτήση Ryanair 4997 προς Thessaloniki (JI4QJF)',
       'Πτήση Aegean Airlines 623 προς Athens (TYPIDE)',
       'Πτήση Aegean Airlines 622 προς Brussels (TZFJCW)',
       'Erroneous Tasks (Εισητήρια)', 'Φίλοι (Μπιλ)',
       'Erroneous Tasks (Ρούχα)', 'Φίλοι (Λώλος)', '<3 (Βιογραφικό)',
       'Πτήση Aegean Airlines 622 προς Brussels (PVWLX2)',
       'Πτήση Aegean Airlines 623 προς Athens (PX2XQZ)',
       'Erroneous Tasks (Τράπεζες - Κάρτες)',
       'Erroneous Tasks (Φώτης Εισητήρια)', 'Erroneous Tasks (CVs)',
       'Οικογένεια (', 'Φίλοι (Παναγιώτης)', 'Φίλοι (Xavier)', nan,
       'Exercise (Τρέξιμο)', 'Exercise (Κολύμβι)', 'Σπίτι (Σούπερμάρκετ)',
       'Erroneous Tasks (Ημερολόγιο)', 'Φίλοι (Καλαθάς, Ερη, Φώτης)',
       'Οικογένεια (Χριστίνα)', 'Hackathon Leuven',
       'Φίλοι (Καλαθάς, Οικονόμου, Τσίτσι)', 'remote',
       'Vdab (Data Analyst NATO)',
       '[Talk] Emotion Detection and Misinformation Harms from Large Language Models by Prof Ananiadou at Women in Data Science WiDS @AUB 2024',
       'Γενέθλια Μουσμούλης', 'ooo', 'Αναχώρηση από το Hôtel Piapia',
       'Άφιξη στο Hôtel Piapia', 'Erroneous Tasks (Eισητήρια)',
       'Erroneous Tasks (Χριστίνα CV)',
       'Αναχώρηση από το Colourful apt,3 stps frm Syntagma,airport line!',
       'Άφιξη στο Colourful apt,3 stps frm Syntagma,airport line!',
       'Φίλοι (Καλαθάς)', 'Φίλοι (Γιατρός)', 'Φιλοσοφική Συζήτηση',
       'Φίλοι ', 'Exercise (Περπάτημα)', '<3 (Μπυράκι)',
       'Φίλοι (Φώτης Έρη)', '<3 (Ψώνια)', 'Erroneous Tasks (Ψώνια)',
       'Φίλοι (Γάμος Παναγιώτη)', 'Φίλοι (Αποστόλης Μπαμπίλας)',
       'Φίλοι (Φώτης)', 'Φίλοι (Βασίλης Άτλας)',
       'MSCA RISE NeuronsXnets Analysis Workshop 2024',
       'Erroneous Tasks (Επιστολική Ψήφος)',
       'Αναχώρηση από το Flat 128 ★ Sea view ★ 5min walk to Roman Forum',
       'Άφιξη στο Flat 128 ★ Sea view ★ 5min walk to Roman Forum',
       'Erroneous Tasks (Αγορές)',
       'Πτήση Aegean Airlines 623 προς Athens (LXLLPY)',
       'Πτήση Aegean Airlines 622 προς Brussels (LY5A9L)',
       'Erroneous Tasks (Συμμάζεμα τα αρχεία)',
       'Erroneous Tasks (Ασφάλεια)', 'Erroneous Tasks (zara)',
       'Erroneous Tasks (Αυτοκίνητο)',
       'Φίλοι (Κίμων, Αποστόλης, Μπαμπίλας)', 'Remote',
       'Erroneous Tasks (Ορκομωσία)', 'Φίλοι (Μιχάλης)',
       'Bevestiging afspraak',
       'Πτήση Aegean Airlines 622 προς Brussels (RRFZ7C)',
       'Πτήση Aegean Airlines 623 προς Athens (RR9SGS)',
       'Φίλοι (Γενέθλια Ορκομωσία)',
       'ΑΠΟΣΤΟΛΟΣ (1) (Απόστολος, Αποστόλης, Τόλης, Αποστολία, Λία, Αποστολίνα, Πολίνα, Αποστολος, Αποστολης, Τολης, Αποστολια, Λια, Αποστολινα, Πολινα)  © www.eortologio.gr',
       'ΟΛΓΑ (Ολγα, Ολγίτσα, Γίτσα, Ολγιτσα, Γιτσα)  © www.eortologio.gr',
       'ΗΛΙΑΣ (Ηλίας, Λιάς, Ηλιάκος, Λιάκος, Λίτσος, Λιάκουρας, Ηλιάνα, Λιάνα, Ηλιας, Λιας, Ηλιακος, Λιακος, Λιτσος, Λιακουρας, Ηλιανα, Λιανα)  © www.eortologio.gr',
       'ΑΝΔΡΟΝΙΚΟΣ (2) (Ανδρόνικος, Ανδρονίκη, Ανδρονικος, Ανδρονικη)  © www.eortologio.gr',
       'Erroneous Tasks (Αγορά Σπιτιού)',
       'Πτήση Aegean Airlines 623 προς Athens (MS869Q)',
       'Πτήση Aegean Airlines 622 προς Brussels (MT8HYI)',
       'Visit Bauwestraat ', 'Erroneous Tasks (Τραγούδι Κίμωνα)',
       'Erroneous Tasks (Ετοίμασε την παρουσίαση)', 'Φίλοι (Άτλας)',
       'Σκόρπιες Σκέψεις', 'Φίλοι (Μπαρίτος)', 'Φίλοι (Σαλέ)',
       'Φίλοι (Αποστόλης)', 'Φίλοι (Shivaji)', 'Φίλοι (Κώστας)',
       'Μετάφραση Μπαμπά', 'Φίλοι ((Βέλγιο - Γαλλία)',
       'Erroneous Tasks (Xavier)', 'Λάμπρος Free',
       'Αναχώρηση από το The Two Carob Trees, Traditional Stonehouse, Nikandri, Pirgos Diros',
       'Άφιξη στο The Two Carob Trees, Traditional Stonehouse, Nikandri, Pirgos Diros',
       'Φίλοι ((Φώτης Αποστόλης)', 'Φίλοι (Γαλλία - Ισπανία Παναγιώτης)',
       'Φίλοι (Thomas)', 'Erroneous Tasks (Φαρμακείο)', 'Blyat',
       'Σπίτι (Κρέπες)', 'Σπίτι (Καθαρισμός Σπιτιού)',
       'Erroneous Tasks (Aegean)', 'Erroneous Tasks (Decathlon)',
       'Σπίτι (Ετοιμασία Φαγητού)', 'Χαζεύω (Τελικός euro)',
       'Οικογένεια (Λάμπρος)', 'Erroneous Tasks (Jeans - Ποδήλατο)',
       '<3 (Τελετή Έναρξης)', 'Περπάτημα',
       'Erroneous Tasks (Erik Meex VTA)', 'Erroneous Tasks (Tηλεσκόπιο)',
       'Γενέθλια της επαφής Kostis Thaniotis',
       'Γενέθλια της επαφής Vasso Asmini', 'Erroneous Tasks (Τηλέφωνο)',
       'Φίλοι (Παναγιώτης Ολυμπιακοί Αγώνες)', 'Οικογένεια (Χρήστος)',
       'Time Dashboard', 'Φίλοι (Basket Atlas)',
       'Erroneous Tasks (Εισητήρια Βουδαπέστη)',
       'Πτήση Aegean Airlines 620 προς Brussels (N2VSF4)',
       'Πτήση Aegean Airlines 623 προς Athens (O2ERLE)',
       'Φίλοι (Ατλας Κόπκο)', 'Erroneous Tasks (Κλήση)', 'Φίλοι (Golf)',
       'Erroneous Tasks (Οδοντίατρος)',
       'Πτήση Aegean Airlines 623 προς Athens (W9R2NC)',
       'Φίλοι (Μπαμπίλας)', 'Erroneous Tasks (Πράγματα)',
       'Erroneous Tasks (Πάρε τα πράγματα από το κουτί)', 'Άρθρο',
       'Πτήση Aegean Airlines 620 προς Brussels (OUIBKM)',
       'Erroneous Tasks (Γράμμα Σκαλιαν)', 'Σπίτι (Σκουπίδια)',
       'Σπίτι ()', 'Erroneous Tasks (Ζωγραφική)', 'Φίλοι (Τσιπούρης)',
       'Φίλοι (Ορέστης)', 'Φίλοι (Γιαμαλής)',
       'Exercise (Σκαλιά + Biceps)', 'Φίλοι (Μουντράκης)',
       'Erroneous Tasks (Αργεντινή)',
       'Πτήση Aegean Airlines 623 προς Athens (UI2PDP)',
       'Πτήση Aegean Airlines 620 προς Brussels (UIDRM8)',
       'Γενέθλια Παπαιωάνου', 'Erroneous Tasks (Καθαρισμός Αυτοκινήτου)',
       'Foto shoot nieuwe/new badges C7! - DIMITRIOS VOGIAS',
       'Erroneous Tasks (Ρούχα Ταξίδι)', 'Erroneous Tasks (Ξενοδοχείο)',
       '<3 (Μασαζ για 2 - Χολαργός)', 'Φίλοι (Atlas)', 'Σπίτι (Ρούχα)',
       'Πτήση Aegean Airlines 623 προς Athens (QNH88F)',
       'Πτήση Aegean Airlines 622 προς Brussels (S8YFIB)',
       'Πτήση Aegean Airlines 623 προς Athens (MB68Z4)',
       'Πτήση Aegean Airlines 622 προς Brussels (MBFY23)',
       'Άρθρο Δημοσίευση', 'Βιβλίο Μπαμπά',
       'Τσέκαρε αν εγκρίθηκε το Smartwatch', 'Φίλοι (Φάσουλ)',
       'Exercise (Pull)', 'Ελιές', 'Φίλοι (Πάνος)',
       'Automated Instagram Poster', 'Erroneous Tasks (CV Χριστίνα)',
       'Exercise (Back)', 'Exercise (Legs)', 'Exercise (Push)',
       'Erroneous Tasks (IKEA)', 'Erroneous Tasks (Βιογραφικά Χριστίνα)',
       'Erroneous Tasks (Αγορά)', 'Exercise (Πόδια)', 'Exercise ()',
       'DIMITRIOS VOGIAS and Dimitra Mastaka',
       'Erroneous Tasks (ημερολόγιο)',
       'Πτήση Aegean Airlines 621 προς Athens (TEXY98)',
       'Φίλοι (Αντωνούλης)', 'Οικογένεια (Φάρσαλα)',
       'Erroneous Tasks (PC Μπαμπά)', 'Οικογένεια ()',
       'Erroneous Tasks (Δώρα Χριστουγέννων)'], dtype=object)

In [6]:
df.Categories.unique()

array([nan, 'Break', 'Holiday', 'Εργασία', 'Χαζεύω', 'Ύπνος',
       'Purple category', 'Οικογένεια', 'Erroneοus Tasks', 'Other',
       'Εισητήρια', 'Φίλοι', 'VDAB', 'Διάβασμα', 'Λάμπρος', 'Σπίτι',
       "Important Don't Miss", 'Exercise', 'Yellow category'],
      dtype=object)

In [10]:
# selection of important values. 
filtered_df = df[
    (df['Subject'].str.contains('Φίλοι|Exercise|Οικογένεια|Erroneous Tasks|<3|Σπίτι|Χαζεύω|Ύπνος|Break|Other|Blyat|Εργασία|Διάβασμα', case=False, na=False)) |
    (df['Categories'] == 'Yellow category')
]

In [11]:
filtered_df

,Subject,Start Date,Start Time,End Time,Description,End Date,Categories
74,Εργασία,9/1/2024,14:00:00,14:30:00,\r\n,9/1/2024,Εργασία
75,Εργασία,8/1/2024,08:00:00,12:00:00,\r\n,8/1/2024,Εργασία
76,Εργασία,5/1/2024,09:00:00,10:00:00,\r\n,5/1/2024,Εργασία
77,Εργασία,3/1/2024,08:20:00,11:00:00,\r\n,3/1/2024,Εργασία
78,Εργασία,4/1/2024,09:00:00,10:30:00,\r\n,4/1/2024,Εργασία
...,...,...,...,...,...,...,...
5165,Οικογένεια,31/12/2024,13:30:00,14:00:00,\r\n,31/12/2024,Οικογένεια
5166,Erroneous Tasks (),31/12/2024,12:30:00,13:30:00,\r\n,31/12/2024,Erroneοus Tasks
5167,Οικογένεια,31/12/2024,12:00:00,12:30:00,\r\n,31/12/2024,Οικογένεια
5168,Οικογένεια,31/12/2024,17:00:00,17:30:00,\r\n,31/12/2024,Οικογένεια
5169,Erroneous Tasks (),31/12/2024,17:30:00,18:00:00,\r\n,31/12/2024,Erroneοus Tasks

In [12]:
# Remove text in parentheses including the parentheses
filtered_df['Subject'] = filtered_df['Subject'].str.replace(r'\(.*?\)', '', regex=True)

# Optional: Strip leading/trailing whitespace
filtered_df['Subject'] = filtered_df['Subject'].str.strip()

C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\1984249921.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Subject'] = filtered_df['Subject'].str.replace(r'\(.*?\)', '', regex=True)
C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\1984249921.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Subject'] = filtered_df['Subject'].str.strip()

In [13]:
filtered_df

,Subject,Start Date,Start Time,End Time,Description,End Date,Categories
74,Εργασία,9/1/2024,14:00:00,14:30:00,\r\n,9/1/2024,Εργασία
75,Εργασία,8/1/2024,08:00:00,12:00:00,\r\n,8/1/2024,Εργασία
76,Εργασία,5/1/2024,09:00:00,10:00:00,\r\n,5/1/2024,Εργασία
77,Εργασία,3/1/2024,08:20:00,11:00:00,\r\n,3/1/2024,Εργασία
78,Εργασία,4/1/2024,09:00:00,10:30:00,\r\n,4/1/2024,Εργασία
...,...,...,...,...,...,...,...
5165,Οικογένεια,31/12/2024,13:30:00,14:00:00,\r\n,31/12/2024,Οικογένεια
5166,Erroneous Tasks,31/12/2024,12:30:00,13:30:00,\r\n,31/12/2024,Erroneοus Tasks
5167,Οικογένεια,31/12/2024,12:00:00,12:30:00,\r\n,31/12/2024,Οικογένεια
5168,Οικογένεια,31/12/2024,17:00:00,17:30:00,\r\n,31/12/2024,Οικογένεια
5169,Erroneous Tasks,31/12/2024,17:30:00,18:00:00,\r\n,31/12/2024,Erroneοus Tasks

In [16]:
# Combine Start Date and Start Time, End Date and End Time into datetime objects
filtered_df['Start DateTime'] = pd.to_datetime(filtered_df['Start Date'] + ' ' + df['Start Time'], format="%d/%m/%Y %H:%M:%S")
filtered_df['End DateTime'] = pd.to_datetime(filtered_df['End Date'] + ' ' + df['End Time'], format="%d/%m/%Y %H:%M:%S")

# Calculate time spent
filtered_df['Time Spent'] = filtered_df['End DateTime'] - filtered_df['Start DateTime']

# Convert the result to minutes
filtered_df['Time Spent (Minutes)'] = filtered_df['Time Spent'].dt.total_seconds() / 60

C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\3847056266.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Start DateTime'] = pd.to_datetime(filtered_df['Start Date'] + ' ' + df['Start Time'], format="%d/%m/%Y %H:%M:%S")
C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\3847056266.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['End DateTime'] = pd.to_datetime(filtered_df['End Date'] + ' ' + df['End Time'], format="%d/%m/%Y %H:%M:%S")
C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\3847056266.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Time Spent'] = filtered_df['End DateTime'] - filtered_df['Start DateTime']
C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\3847056266.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Time Spent (Minutes)'] = filtered_df['Time Spent'].dt.total_seconds() / 60

In [31]:
filtered_df

,Subject,Start Date,Start Time,End Time,Description,End Date,Categories,Start DateTime,End DateTime,Time Spent,Time Spent (Minutes),Month,Day
74,Εργασία,9/1/2024,14:00:00,14:30:00,\r\n,9/1/2024,Εργασία,2024-01-09 14:00:00,2024-01-09 14:30:00,0 days 00:30:00,30.0,January,9
75,Εργασία,8/1/2024,08:00:00,12:00:00,\r\n,8/1/2024,Εργασία,2024-01-08 08:00:00,2024-01-08 12:00:00,0 days 04:00:00,240.0,January,8
76,Εργασία,5/1/2024,09:00:00,10:00:00,\r\n,5/1/2024,Εργασία,2024-01-05 09:00:00,2024-01-05 10:00:00,0 days 01:00:00,60.0,January,5
77,Εργασία,3/1/2024,08:20:00,11:00:00,\r\n,3/1/2024,Εργασία,2024-01-03 08:20:00,2024-01-03 11:00:00,0 days 02:40:00,160.0,January,3
78,Εργασία,4/1/2024,09:00:00,10:30:00,\r\n,4/1/2024,Εργασία,2024-01-04 09:00:00,2024-01-04 10:30:00,0 days 01:30:00,90.0,January,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5165,Οικογένεια,31/12/2024,13:30:00,14:00:00,\r\n,31/12/2024,Οικογένεια,2024-12-31 13:30:00,2024-12-31 14:00:00,0 days 00:30:00,30.0,December,31
5166,Erroneous Tasks,31/12/2024,12:30:00,13:30:00,\r\n,31/12/2024,Erroneοus Tasks,2024-12-31 12:30:00,2024-12-31 13:30:00,0 days 01:00:00,60.0,December,31
5167,Οικογένεια,31/12/2024,12:00:00,12:30:00,\r\n,31/12/2024,Οικογένεια,2024-12-31 12:00:00,2024-12-31 12:30:00,0 days 00:30:00,30.0,December,31
5168,Οικογένεια,31/12/2024,17:00:00,17:30:00,\r\n,31/12/2024,Οικογένεια,2024-12-31 17:00:00,2024-12-31 17:30:00,0 days 00:30:00,30.0,December,31
5169,Erroneous Tasks,31/12/2024,17:30:00,18:00:00,\r\n,31/12/2024,Erroneοus Tasks,2024-12-31 17:30:00,2024-12-31 18:00:00,0 days 00:30:00,30.0,December,31

In [32]:
# Add Month and Day columns
filtered_df['Month'] = filtered_df['Start DateTime'].dt.strftime('%B')  # Month name
filtered_df['Day'] = filtered_df['Start DateTime'].dt.day

C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\2569579152.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\a00556457\AppData\Local\Temp\ipykernel_28804\2569579152.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [40]:
filtered_df.to_csv('filtered_data.csv')